version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=jokes
    depends_on:
      - postgres

  documentation:
    build:
      context: .
      dockerfile: Dockerfile.documentation
    ports:
      - "9966:9966"
    networks:
      - app-network
    volumes:
      - ./documentation:/app/documentation

  postgres:
    image: postgres:17.2-alpine
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=jokes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/cmd/server/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: