FROM golang:1.23.6-alpine

WORKDIR /app

# Install required system dependencies
RUN apk add --no-cache gcc musl-dev

# Copy go mod files
COPY backend/go.mod backend/go.sum ./

# Download dependencies
RUN go mod download

# Copy source code and .env file
COPY backend/cmd/server ./cmd/server
COPY backend/cmd/server/.env ./.env  

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server

# Expose port
EXPOSE 8080

# Run the application
CMD ["./main"]